export const MAP_DATA = [
    // --- Christmas Events (Eventos de Navidad) ---
    {
        id: 'xmas-1',
        type: 'moop',
        title: 'Fira de Santa Llúcia',
        emoji: '🎄',
        location: 'Plaça del Doctor Robert',
        lat: 41.54659,
        lng: 2.1088,
        attendees: 150,
        category: 'Cultura',
        image: '/assets/fira.png',
        time: '10:00 - 21:00',
        description: 'Paseo ideal para ver figuritas de pesebre, musgo y artesanía. Muy colorido para los pequeños.',
        tags: ['Navidad', 'Feria', 'Artesanía'],
        isLive: true
    },
    {
        id: 'xmas-5',
        type: 'moop',
        title: 'El Llaminer y Calendario',
        emoji: '🍫',
        location: 'Racó del Campanar',
        lat: 41.5471,
        lng: 2.1086,
        attendees: 350,
        category: 'Espectáculo',
        image: '/assets/lightshow.png', // Reusing lightshow or create specialized character later. Using lightshow for "show" vibe.
        time: '18:45 - 19:30',
        description: 'El personaje principal de la Navidad en Sabadell abre una ventana gigante del calendario con un espectáculo.',
        tags: ['Navidad', 'Infantil', 'Show'],
        isLive: true
    },
    {
        id: 'xmas-3',
        type: 'moop',
        title: 'Pista de Hielo',
        emoji: '⛸️',
        location: "Jardins de l'Eix Macià",
        lat: 41.5517, // Near Parc Catalunya/Eix Macia coordinates
        lng: 2.0935,
        attendees: 120,
        category: 'Deporte',
        image: '/assets/icerink.png',
        time: 'Abierto',
        description: 'Patinaje sobre hielo auténtico. Una actividad estrella de la Navidad para divertirse en familia.',
        tags: ['Navidad', 'Hielo', 'Familia'],
        isLive: true
    },
    {
        id: 'xmas-train',
        type: 'moop',
        title: 'Carrilet de Nadal',
        emoji: '🚂',
        location: 'Ejes Comerciales (Centro)',
        lat: 41.5475, // Starting near Plaça Major
        lng: 2.1088,
        attendees: 60,
        category: 'Infantil',
        image: '/assets/train.png',
        time: 'Ruta Continua',
        description: 'Tren turístico infantil que recorre las principales calles comerciales adornadas con iluminación.',
        tags: ['Navidad', 'Tren', 'Infantil'],
        isLive: true
    },
    {
        id: 'xmas-2',
        type: 'moop',
        title: 'Espectáculo de Agua y Luz',
        emoji: '✨',
        location: 'Passeig de la Plaça Major',
        lat: 41.5475,
        lng: 2.1088,
        attendees: 300,
        category: 'Espectáculo',
        image: '/assets/lightshow.png',
        time: '18:50 / 19:05 / 19:20',
        description: 'Show de luces y música sincronizado con las fuentes, muy visual para los niños.',
        tags: ['Navidad', 'Luces', 'Música'],
        isLive: true
    },
    {
        id: 'xmas-lanterns',
        type: 'moop',
        title: 'Fanalets de Reis',
        emoji: '🏮',
        location: 'Biblioteca de Ponent',
        lat: 41.5560,
        lng: 2.0890,
        attendees: 25,
        category: 'Taller',
        image: '/assets/lanterns.png',
        time: 'Mar 9 dic - 18:30',
        description: 'Taller para que los niños preparen sus propios farolillos para la Cabalgata de Reyes.',
        tags: ['Taller', 'Reyes', 'Infantil'],
        isLive: true
    },
    {
        id: 'xmas-workshop',
        type: 'moop',
        title: 'Taller Infantil',
        emoji: '🎨',
        location: 'Biblioteca dels Safareigs',
        lat: 41.5544,
        lng: 2.1012,
        attendees: 20,
        category: 'Taller',
        image: '/assets/lanterns.png', // Reusing workshop vibe img
        time: 'Jue 11 dic - 17:30',
        description: 'Actividad de manualidades o temática navideña para niños a partir de 7 años.',
        tags: ['Taller', 'Infantil', 'Manualidades'],
        isLive: true
    },
    {
        id: 'xmas-4',
        type: 'moop',
        title: '48a Exposició de Pessebres',
        emoji: '👼',
        location: 'Acadèmia Catòlica',
        lat: 41.5460,
        lng: 2.1100,
        attendees: 45,
        category: 'Exposición',
        image: '/assets/fira.png', // Fits the theme
        time: 'Abierto',
        description: 'Exposición de belenes, un plan cultural tradicional para hacer con la familia.',
        tags: ['Cultura', 'Tradición'],
        isLive: true
    },
    {
        id: 'xmas-fansa',
        type: 'moop',
        title: 'Feria de Artesanía FANSA',
        emoji: '🧶',
        location: 'Plaça Doctor Robert',
        lat: 41.5465,
        lng: 2.1088,
        attendees: 80,
        category: 'Feria',
        image: '/assets/market.png',
        time: 'Abre 12 dic',
        description: 'Feria de artesanía local para encontrar regalos y productos únicos.',
        tags: ['Feria', 'Artesanía', 'Regalos'],
        isLive: true
    },

    // --- Activities & Places (Actividades y Lugares) ---
    {
        id: 'act-tower',
        type: 'moop',
        title: 'Visita Torre del Agua',
        emoji: '🏰',
        location: 'Eix Macià (H. Taulí)',
        lat: 41.5552,
        lng: 2.1131,
        attendees: 15,
        category: 'Turismo',
        image: '/assets/tower.png',
        time: 'Fines de semana',
        description: 'Icono modernista. Visita para conocer la historia industrial y arquitectónica.',
        tags: ['Turismo', 'Historia', 'Vistas'],
        isLive: true
    },
    {
        id: 'act-mhs-expo',
        type: 'moop',
        title: 'Sabadell en el recuerdo',
        emoji: '📜',
        location: "Museu d'Història",
        lat: 41.5481,
        lng: 2.1077,
        attendees: 10,
        category: 'Exposición',
        image: '/assets/museum.png',
        time: 'Abierto',
        description: 'Muestra de fotografías antiguas y elementos históricos que repasan la vida de la ciudad.',
        tags: ['Cultura', 'Historia', 'Museo'],
        isLive: true
    },
    {
        id: 'act-belltower',
        type: 'moop',
        title: 'Campanar de Sant Fèlix',
        emoji: '🔔',
        location: 'Plaça de Sant Roc',
        lat: 41.5471,
        lng: 2.1086,
        attendees: 30,
        category: 'Turismo',
        image: '/assets/belltower.png',
        time: 'Fines de semana',
        description: 'Sube al campanario gótico para tener unas vistas panorámicas del centro.',
        tags: ['Vistas', 'Turismo', 'Foto'],
        isLive: true
    },
    {
        id: 'act-park',
        type: 'moop',
        title: 'Ruta Parc de Catalunya',
        emoji: '🌳',
        location: 'Parc de Catalunya',
        lat: 41.5517,
        lng: 2.0935,
        attendees: 200,
        category: 'Aire Libre',
        image: '/assets/park.png',
        time: 'Libre',
        description: 'El principal pulmón verde de la ciudad. Ideal para pasear, deporte o bicicleta.',
        tags: ['Naturaleza', 'Deporte', 'Relax'],
        isLive: true
    },
    {
        id: 'act-workshop-adults',
        type: 'moop',
        title: "Taller de 'Nadal' (Adultos)",
        emoji: '✂️',
        location: 'Can Rull (Centro Cívico)',
        lat: 41.5530,
        lng: 2.0850,
        attendees: 12,
        category: 'Taller',
        image: '/assets/lanterns.png', // Crafting image
        time: 'Mié 10 dic - 18:00',
        description: 'Taller de manualidades navideñas o decoración, dirigido al público adulto.',
        tags: ['Taller', 'Manualidades', 'Adultos'],
        isLive: true
    },
    {
        id: 'act-choir',
        type: 'moop',
        title: 'Concierto de Nadal',
        emoji: '🎵',
        location: 'Església Santíssima Trinitat',
        lat: 41.5411,
        lng: 2.1113,
        attendees: 100,
        category: 'Música',
        image: '/assets/choir.png',
        time: 'Sáb 13 dic - 19:30',
        description: 'Concierto de coro local con repertorio especial de villancicos.',
        tags: ['Música', 'Navidad', 'Concierto'],
        isLive: true
    },
    {
        id: 'act-market',
        type: 'moop',
        title: 'Mercat Central',
        emoji: '🍅',
        location: 'Plaça Mercat',
        lat: 41.5473,
        lng: 2.1050,
        attendees: 500,
        category: 'Gastronomía',
        image: '/assets/market.png',
        time: 'Mañanas L-S',
        description: 'Punto de encuentro gastronómico. Mercado semanal los martes y jueves.',
        tags: ['Mercado', 'Comida', 'Local'],
        isLive: true
    },
    {
        id: 'act-forest',
        type: 'moop',
        title: 'Bosque de Can Deu',
        emoji: '🌲',
        location: 'Can Deu (Noroeste)',
        lat: 41.5750,
        lng: 2.0800,
        attendees: 40,
        category: 'Naturaleza',
        image: '/assets/forest.png',
        time: 'Libre',
        description: 'Escapada a la naturaleza, perfecta para una caminata o una ruta de trail.',
        tags: ['Naturaleza', 'Senderismo', 'Relax'],
        isLive: true
    },

    // --- Live Moops (Social User Events) ---
    {
        id: 'moop-cafe',
        type: 'moop',
        title: 'Café y charla tranquis',
        emoji: '☕',
        location: "Café'ina (Centro)",
        lat: 41.5438,
        lng: 2.1105,
        attendees: 3,
        capacity: 4,
        category: 'Social',
        image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=1080',
        time: 'Empieza en 15 min',
        description: 'Café tranquilo para desconectar un rato y charlar de todo un poco.',
        tags: ['Tranquilo', 'Café', 'Social'],
        host: { name: 'Ana M.', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d' },
        affinity: 98,
        isLive: true
    },
    {
        id: 'moop-running',
        type: 'moop',
        title: 'Running 5km',
        emoji: '🏃',
        location: 'Parc Catalunya',
        lat: 41.551,
        lng: 2.100,
        attendees: 2,
        capacity: 5,
        category: 'Deporte',
        image: 'https://images.unsplash.com/photo-1552674605-4694042af4fc?q=80&w=1080',
        time: 'Empieza en 30 min',
        description: 'Salida de running suave por el parque. Ritmo 5:30 min/km.',
        tags: ['Activo', 'Deporte', 'Running'],
        host: { name: 'Marc R.', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d' },
        affinity: 95,
        isLive: true
    }
];
